### ISSUE TITLE
Directive name

### ISSUE THREAD

**Issue by EladBezalel** [cesar-garay/zoom-directive#1]
First of all thank you for the hard work, this looks very nice,

I would suggest a rename for the directive to be: `cg-zoom` because `angular-zoom-directive` is way too much and the `directive` part is also self-explanatory.
Besides that i'd also look for a way to remove the dependency on ngMaterial since the only use of it is the `$mdGesture` service, without ngMaterial your directive can be used in **any** angular app that have images, which is cool :smile: 

keep up with the good work :)

**Comment by devversion** [comment]
I recommend `HammerJS` for the gesture handling.

It works pretty similar to the `$mdGesture` service of ngMaterial.

**Comment by cesar-garay** [comment]
Hi Guys, thanks so much for your comments. I'll take a look on HammerJs.
I'll update the directive name to make it simpler.
Thanks so much for your time !
